version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  evals: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  testing-setup-command:
    docker:
      - image: cimg/base:current-22.04
    parameters:
      eval_platform:
        type: string
        description: eval platform name
        enum:
          - braintrust
          - langsmith
          - ""
    steps:
      - evals/setup:
          eval_platform: << parameters.eval_platform >>
      - run:
          name: Verify evals/setup braintrust
          command: which cci-<< parameters.eval_platform >>-eval

workflows:
  test-deploy:
    jobs:
      - testing-setup-command:
          eval_platform: braintrust
          filters: *filters
      - testing-setup-command:
          name: Test Setup Command langsmith
          eval_platform: langsmith
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: circleci/evals
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - testing-setup-command
          context: Circleci-Ai-Orb-Publishing
          filters: *release-filters
